<template><MainLayout><div class="p-6 space-y-5"><div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Pedidos Rappi</h1><p class="text-sm text-gray-500">Acepta, rechaza y revisa pedidos recibidos desde Rappi.</p></div><BaseButton variant="outline" :loading="loading" @click="load">Actualizar</BaseButton></div>
<BaseAlert v-if="errorText" variant="danger">{{ errorText }}</BaseAlert><BaseLoading v-if="loading" text="Cargando pedidos Rappi..." />
<div v-else-if="!orders.length" class="rounded-lg border border-dashed bg-white py-16 text-center text-gray-500">No hay pedidos Rappi recibidos.</div>
<div v-else class="grid gap-4"><BaseCard v-for="order in orders" :key="order.id"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold">Rappi #{{ order.externalOrderId }}</h2><p class="text-sm text-gray-500">{{ order.customerName || 'Cliente Rappi' }} · {{ order.deliveryAddress || 'Entrega administrada por Rappi' }}</p></div><div class="text-right"><p class="font-bold">${{ order.total.toLocaleString('es-CO') }}</p><span class="rounded-full bg-amber-100 px-2 py-1 text-xs">{{ statusLabel(order.status) }}</span></div></div>
<ul class="mt-3 border-t pt-3 text-sm"><li v-for="line in order.lines" :key="line.externalProductId">{{ line.quantity }} × {{ line.name }} — ${{ line.unitPrice.toLocaleString('es-CO') }} <span v-if="line.notes" class="text-gray-500">({{ line.notes }})</span></li></ul>
<BaseAlert v-if="order.lastError" class="mt-3" variant="danger">{{ order.lastError }}</BaseAlert><div v-if="canDecide(order.status)" class="mt-4 flex justify-end gap-2"><BaseButton variant="danger" size="sm" :loading="workingId===order.id" @click="reject(order.id)">Rechazar</BaseButton><BaseButton size="sm" :loading="workingId===order.id" :disabled="order.status==='blocked_mapping'" @click="accept(order.id)">Aceptar y enviar a cocina</BaseButton></div></BaseCard></div></div></MainLayout></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import MainLayout from '@/components/layout/MainLayout.vue'; import BaseButton from '@/components/ui/BaseButton.vue'; import BaseCard from '@/components/ui/BaseCard.vue'; import BaseAlert from '@/components/ui/BaseAlert.vue'; import BaseLoading from '@/components/ui/BaseLoading.vue'; import { integrationApi } from '@/services/MainAPI/integrationApi'; import type { RappiExternalOrder } from '@/types/integrations'
const route=useRoute(),router=useRouter(),orders=ref<RappiExternalOrder[]>([]),loading=ref(false),workingId=ref<number|null>(null),errorText=ref('');const branchId=()=>route.query.branchId?Number(route.query.branchId):null
async function load(){loading.value=true;errorText.value='';try{orders.value=(await integrationApi.getRappiOrders(branchId())).data}catch(e:any){errorText.value=e.message}finally{loading.value=false}}
async function accept(id:number){workingId.value=id;try{const r=await integrationApi.acceptRappiOrder(id);await load();if(r.data.internalOrderId)void router.push(`/orders/${r.data.internalOrderId}`)}catch(e:any){errorText.value=e.message}finally{workingId.value=null}}
async function reject(id:number){workingId.value=id;try{await integrationApi.rejectRappiOrder(id);await load()}catch(e:any){errorText.value=e.message}finally{workingId.value=null}}
const canDecide=(s:string)=>['new','pending_acceptance','blocked_mapping','sync_error'].includes(s);const statusLabel=(s:string)=>({new:'Nuevo',blocked_mapping:'Bloqueado por mapeo',pending_acceptance:'Pendiente',processing:'Procesando',accepted:'Aceptado',rejected:'Rechazado',cancelled:'Cancelado',sync_error:'Error de sincronización'}[s]||s)
onMounted(load)
</script>
